/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.1.119 */
/* Module Version: 5.7 */
/* Tue Jun 27 13:02:36 2017 */

/* parameterized module instance */
sys_pll __ (.CLKI( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
